language: rust
rust:
- nightly
before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build -- --features "$FEATURES" &&
  travis-cargo test -- --features "$FEATURES" &&
  travis-cargo bench -- --features "$FEATURES" &&
  travis-cargo doc -- --features "$FEATURES"
after_success:
- if [ -z "$FEATURES" ]; then travis-cargo doc-upload; fi
env:
  matrix:
  - FEATURES=''
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=unstable
  - secure: tGxXnSWSs7UCvga7/gEG3nK7Z2GXJeCgStPcmEs59i/yC1vQb26Wk79+GswNdsqCKfWy7VxQU2kNLXif2Cnvw01qbQcJZ+QMhwviEyM/R8v+RuQfvPjf0NOFW7qBi4B99CaXWWzTbCKIPq/zBrSghA78YpSJ4xcqm//y7SbjR/gjzp/35/4DspsxQFeAjYHG3oFprNM3pt5KLNBfSmmX0Ebau1jx/qps52SE2DbZE2vcIdcNoHw/TLRmvFNeqFYS1iM+KRHGag9oxuFENWRR6qw86yRkToTuocVqwxzXLqqpoYiuFOq07COx+Ztr9gbjZpnYSQ04flIlJwFvUBQF+lvcG5XhXYCPmeYceiM+QpExBb9ttS6FBq3mymipGxa2Dwu7yjQNh183xxzRDQ0MRr8y3sWw9i1+4JL4LoLnQlKLkSqH/UBP3JcibZyEI3rqsxCtsFZ6kMzQ4r/IlY26cVeLHsj2KHfBHETBkAtLLiv3GtIIblz6XXMyW+Y6cQX8JTUXqzMP1NdECV++LnGJEPPB5RXzZVf98CHteR9+yNffdeSpDlujzl1bMGFBQV1hWXg/npw+KD03o3J9z21r+ejdZsWAYlqiHoFR0VjwRh/PMTjwm6HI71/ndWwqNs0d6RCGIQerwTdJ/1b5paXMUO/rAEL9bv87Upx96HvLTm0=
